project:
  type: website
website:
  title: Personal Notes
  sidebar:
    style: docked
    search: true
    contents:
    - text: Home
      href: index.qmd
    - section: math
      contents:
      - section: MATH 451
        contents:
        - text: Epsilon-Delta Continuity
          href: notes/math/MATH_451/epsilon-delta-continuity.qmd
      - section: MATH 457
        contents:
        - text: note 1
          href: notes/math/MATH_457/note-1.qmd
        - text: Epsilon-Delta Continuity
          href: notes/math/MATH_457/epsilon-delta-continuity.qmd
  page-navigation: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
