project:
  type: website
website:
  title: Personal Notes
  sidebar:
    style: docked
    search: true
    contents:
    - text: Home
      href: index.qmd
    - section: math
      contents:
      - section: Complex Variables
        contents:
        - text: Introduction
          href: notes/math/Complex_Variables/introduction.qmd
      - section: Math Stats w Applications I
        contents:
        - text: Introduction
          href: notes/math/Math_Stats_w_Applications_I/introduction.qmd
        - text: Method of Moments
          href: notes/math/Math_Stats_w_Applications_I/method-of-moments.qmd
      - section: Stochastic Processes
        contents:
        - text: Introduction
          href: notes/math/Stochastic_Processes/introduction.qmd
  page-navigation: true
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
